// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nizzswcvdyunkwnilztf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5penpzd2N2ZHl1bmt3bmlsenRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTc4MTUsImV4cCI6MjA2NzkzMzgxNX0.UM0LRuSloxcVWPFMvRMW8oR6ip9KTM4xIWRFtT6letY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});